### ISSUE TITLE
All Vega rendering components are broken

### ISSUE THREAD

**Issue by wadethestealth** [nteract/hydrogen#1771]
All Vega React components don't show any props inside `supportedMedia`, and therefore output can not be routed to their display because it is missing the default `mediaType` prop.

@BenRussert

**Comment by wadethestealth** [comment]
The work around for now is to downgrade to hydrogen 2.10.3 for your previously supported Vegas however it's impossible to use the newer Vegas

@phromo

**Comment by qchenevier** [comment]
Downgrading is a bit tricky due to #1716 .

Here are the steps to downgrade to Hydrogen 2.10.3:

```
apm remove Hydrogen
apm install Hydrogen@2.10.3
cd ~/.atom/packages/Hydrogen
npm install --save @nteract/presentational-components
```

Then import altair with Vegalite 2 in your python code:
```python
import altair.vegalite.v2 as alt # instead of "import altair as alt"
```

**Comment by wadethestealth** [comment]
@qchenevier I don't think that's the right pr

**Comment by qchenevier** [comment]
> @qchenevier I don't think that's the right pr

Corrected, thanks.

**Comment by phromo** [comment]
@wadethestealth can you throw some more detailed  pointers to the work needed to resolve this? In what you mention above, is that changes needed in Hydrogen or Vega/Vegalite? Maybe I could help through a PR if you point the way.

I'm currently using `alt.renderers.enable('png')` as a workaround to avoid downgrading.

**Comment by wadethestealth** [comment]
@phromo if you view the PR related to upgrading to support the newer Vegas their is a linked to nteract/nteract where the Vega transforms package was updated. What I know is that there were some changes there, but it could also be due to the PR that refractors our transforms.

**Comment by wadethestealth** [comment]
I was correct about nteract/nteract#4442. It seems that the `defaultProps` were left out in the refactor, so now I have fixed that, and will be awaiting the newest release of @nteract/transform-vega set to be published 9-30-19. In which case you will have all the vegas at your disposal. 😄 @phromo

**Comment by wadethestealth** [comment]
Anyone who still faces this issue should reinstall hydrogen, or if you are more familiar with npm then you need to upgrade @nteract/transform-vega to atleast 6.0.2.

**Comment by rpalloni** [comment]
Hello, does the issue still require hydrogen 2.10? I'm in hydrogen 2.14 / atom 1.44 / Ubuntu 18.04 / python 3.7 / altair 2 (or 4) and I cannot plot images with this code

import altair as alt

# load a simple dataset as a pandas DataFrame
from vega_datasets import data
cars = data.cars()

fig = alt.Chart(cars).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
).interactive()

fig

-- fig.to_dict()    data are in
