### ISSUE TITLE
In Atom install of hydrogen@2.15.0 fails

### ISSUE THREAD

**Issue by mattcbro** [nteract/hydrogen#2089]
```
$ apm --version
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.48.0
python 
git 2.25.1
```

I'm on linux mint 20.1 Cinnamon.  Here is the rather lengthy error message from the install script:

```
$ apm install hydrogen@2.15.0
Installing hydrogen@2.15.0 to /home/matt/.atom/packages ✗

> @aminya/zeromq@5.2.12 install /tmp/apm-install-dir-2021316-49845-1hsi6mt.52e1/node_modules/Hydrogen/node_modules/@aminya/zeromq
> node-gyp-build || npm run build:libzmq

make: Entering directory '/tmp/apm-install-dir-2021316-49845-1hsi6mt.52e1/node_modules/Hydrogen/node_modules/@aminya/zeromq/build'
  CXX(target) Release/obj.target/zmq/binding.o
  SOLINK_MODULE(target) Release/obj.target/zmq.node
make: Leaving directory '/tmp/apm-install-dir-2021316-49845-1hsi6mt.52e1/node_modules/Hydrogen/node_modules/@aminya/zeromq/build'

> @aminya/zeromq@5.2.12 build:libzmq /tmp/apm-install-dir-2021316-49845-1hsi6mt.52e1/node_modules/Hydrogen/node_modules/@aminya/zeromq
> node scripts/preinstall.js && node-gyp rebuild

Building libzmq for linux

npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
In file included from /home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13,
                 from /home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from ../binding.cc:24:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:307:49: warning: ‘BufferReference’ is deprecated: Use MemorySpan<const uint8_t> [-Wdeprecated-declarations]
  307 |   declarator __attribute__((deprecated(message)))
      |                                                 ^
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:4444:3: note: in expansion of macro ‘V8_DEPRECATED’
 4444 |   V8_DEPRECATED("Use CompiledWasmModule::GetWireBytesRef()",
      |   ^~~~~~~~~~~~~
In file included from ../binding.cc:24:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:4386:58: note: declared here
 4386 |   V8_DEPRECATED("Use MemorySpan<const uint8_t>", struct) BufferReference {
      |                                                          ^~~~~~~~~~~~~~~
In file included from /home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13,
                 from /home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from ../binding.cc:24:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:307:49: warning: ‘v8::WasmModuleObject::SerializedModule’ is deprecated: Use OwnedBuffer [-Wdeprecated-declarations]
  307 |   declarator __attribute__((deprecated(message)))
      |                                                 ^
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:4457:3: note: in expansion of macro ‘V8_DEPRECATED’
 4457 |   V8_DEPRECATED("Use CompiledWasmModule::Serialize()",
      |   ^~~~~~~~~~~~~
In file included from ../binding.cc:24:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:4380:55: note: declared here
 4380 |   std::pair<std::unique_ptr<const uint8_t[]>, size_t> SerializedModule;
      |                                                       ^~~~~~~~~~~~~~~~
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h: In member function ‘v8::Local<v8::Boolean> v8::Value::ToBoolean() const’:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:10172:62: warning: ‘v8::MaybeLocal<v8::Boolean> v8::Value::ToBoolean(v8::Local<v8::Context>) const’ is deprecated: ToBoolean can never throw. Use Local version. [-Wdeprecated-declarations]
10172 |   return ToBoolean(Isolate::GetCurrent()->GetCurrentContext())
      |                                                              ^
In file included from /home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13,
                 from /home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from ../binding.cc:24:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:2388:63: note: declared here
 2388 |                     V8_WARN_UNUSED_RESULT MaybeLocal<Boolean> ToBoolean(
      |                                                               ^~~~~~~~~
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
  322 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../binding.cc:40:
../../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../../nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2298 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
../binding.cc: In member function ‘void zmq::Socket::NotifyReadReady()’:
../binding.cc:399:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  399 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 0, NULL);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1024:46: note: declared here
 1024 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc:399:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  399 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 0, NULL);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1024:46: note: declared here
 1024 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc: In member function ‘void zmq::Socket::NotifySendReady()’:
../binding.cc:407:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  407 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 0, NULL);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1024:46: note: declared here
 1024 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc:407:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  407 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 0, NULL);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1024:46: note: declared here
 1024 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc: In member function ‘void zmq::Socket::MonitorEvent(uint16_t, int32_t, char*)’:
../binding.cc:458:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  458 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 4, argv);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1024:46: note: declared here
 1024 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc:458:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  458 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 4, argv);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1024:46: note: declared here
 1024 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc: In member function ‘void zmq::Socket::MonitorError(const char*)’:
../binding.cc:473:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  473 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 1, argv);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1024:46: note: declared here
 1024 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc:473:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  473 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 1, argv);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1024:46: note: declared here
 1024 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc: In static member function ‘static void zmq::Socket::UV_MonitorCallback(uv_timer_t*, int)’:
../binding.cc:545:98: warning: cast between incompatible function types from ‘void (*)(uv_timer_t*, int)’ {aka ‘void (*)(uv_timer_s*, int)’} to ‘uv_timer_cb’ {aka ‘void (*)(uv_timer_s*)’} [-Wcast-function-type]
  545 |       uv_timer_start(s->monitor_handle_, reinterpret_cast<uv_timer_cb>(Socket::UV_MonitorCallback), s->timer_interval_, 0);
      |                                                                                                  ^
../binding.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE zmq::Socket::Bind(Nan::NAN_METHOD_ARGS_TYPE)’:
../binding.cc:779:37: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  779 |                   (uv_after_work_cb)UV_BindAsyncAfter);
      |                                     ^~~~~~~~~~~~~~~~~
../binding.cc: In static member function ‘static void zmq::Socket::UV_BindAsyncAfter(uv_work_t*)’:
../binding.cc:814:70: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  814 |     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, 1, argv);
      |                                                                      ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1024:46: note: declared here
 1024 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc:814:70: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  814 |     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, 1, argv);
      |                                                                      ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1024:46: note: declared here
 1024 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE zmq::Socket::Unbind(Nan::NAN_METHOD_ARGS_TYPE)’:
../binding.cc:860:37: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  860 |                   (uv_after_work_cb)UV_UnbindAsyncAfter);
      |                                     ^~~~~~~~~~~~~~~~~~~
../binding.cc: In static member function ‘static void zmq::Socket::UV_UnbindAsyncAfter(uv_work_t*)’:
../binding.cc:893:70: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  893 |     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, 1, argv);
      |                                                                      ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1024:46: note: declared here
 1024 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc:893:70: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  893 |     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, 1, argv);
      |                                                                      ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1024:46: note: declared here
 1024 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE zmq::Socket::Monitor(Nan::NAN_METHOD_ARGS_TYPE)’:
../binding.cc:1122:103: warning: cast between incompatible function types from ‘void (*)(uv_timer_t*, int)’ {aka ‘void (*)(uv_timer_s*, int)’} to ‘uv_timer_cb’ {aka ‘void (*)(uv_timer_s*)’} [-Wcast-function-type]
 1122 |       uv_timer_start(socket->monitor_handle_, reinterpret_cast<uv_timer_cb>(Socket::UV_MonitorCallback), timer_interval, 0);
      |                                                                                                       ^
In file included from ../binding.cc:25:
../binding.cc: At global scope:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:560:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  560 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:594:3: note: in expansion of macro ‘NODE_MODULE_X’
  594 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../binding.cc:1558:1: note: in expansion of macro ‘NODE_MODULE’
 1558 | NODE_MODULE(zmq, init)
      | ^~~~~~~~~~~
In file included from ../binding.cc:24:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node_object_wrap.h:84:78:   required from here
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:9634:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
 9634 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../../nan/nan_object_wrap.h:65:61:   required from here
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:9634:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
g++: error: ./Release/../../zmq/lib/libzmq.a: No such file or directory
make: *** [zmq.target.mk:136: Release/obj.target/zmq.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-72-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-2021316-49845-1hsi6mt.52e1/node_modules/Hydrogen/node_modules/@aminya/zeromq
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
/tmp/apm-install-dir-2021316-49845-1hsi6mt.52e1/node_modules/Hydrogen/node_modules/@aminya/zeromq/scripts/preinstall.js:20
  child.stdout.pipe(process.stdout);
               ^

TypeError: Cannot read property 'pipe' of undefined
    at buildZMQ (/tmp/apm-install-dir-2021316-49845-1hsi6mt.52e1/node_modules/Hydrogen/node_modules/@aminya/zeromq/scripts/preinstall.js:20:16)
    at IncomingMessage.<anonymous> (/tmp/apm-install-dir-2021316-49845-1hsi6mt.52e1/node_modules/Hydrogen/node_modules/@aminya/zeromq/scripts/preinstall.js:107:5)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @aminya/zeromq@5.2.12 build:libzmq: `node scripts/preinstall.js && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @aminya/zeromq@5.2.12 build:libzmq script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/matt/.atom/.apm/_logs/2021-04-17T03_31_41_138Z-debug.log
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-2021316-49845-1hsi6mt.52e1/package.json'
npm WARN apm-install-dir-2021316-49845-1hsi6mt.52e1 No description
npm WARN apm-install-dir-2021316-49845-1hsi6mt.52e1 No repository field.
npm WARN apm-install-dir-2021316-49845-1hsi6mt.52e1 No README data
npm WARN apm-install-dir-2021316-49845-1hsi6mt.52e1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @aminya/zeromq@5.2.12 install: `node-gyp-build || npm run build:libzmq`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @aminya/zeromq@5.2.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/matt/.atom/.apm/_logs/2021-04-17T03_31_41_623Z-debug.log
```

**Comment by aminya** [comment]
The issue is already fixed. Install the latest Hydrogen which is 0.15.3

```
apm install hydrogen#0.15.3
```

**Comment by mattcbro** [comment]
I still have a problem sad to say.  Something's up with the zeromq install, whatever that is.  Should I uninstall my system libzmq?
```
$ apm install hydrogen#0.15.3
Installing hydrogen#0.15.3 to /home/matt/.atom/packages 
✗

> @aminya/zeromq@5.2.15 install /tmp/apm-install-dir-2021316-60588-v18t2r.5ecp/node_modules/Hydrogen/node_modules/@aminya/zeromq
> node-gyp-build || npm run build:libzmq

make: Entering directory '/tmp/apm-install-dir-2021316-60588-v18t2r.5ecp/node_modules/Hydrogen/node_modules/@aminya/zeromq/build'
  ACTION binding_gyp_libzmq_target_prepare_build zmq/BUILD_SUCCESS
Building libzmq for linux
  TOUCH Release/obj.target/libzmq.stamp
  CXX(target) Release/obj.target/zmq/binding.o
  SOLINK_MODULE(target) Release/obj.target/zmq.node
make: Leaving directory '/tmp/apm-install-dir-2021316-60588-v18t2r.5ecp/node_modules/Hydrogen/node_modules/@aminya/zeromq/build'

> @aminya/zeromq@5.2.15 build:libzmq /tmp/apm-install-dir-2021316-60588-v18t2r.5ecp/node_modules/Hydrogen/node_modules/@aminya/zeromq
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-2021316-60588-v18t2r.5ecp/node_modules/Hydrogen/node_modules/@aminya/zeromq/build'
  ACTION binding_gyp_libzmq_target_prepare_build zmq/BUILD_SUCCESS
Building libzmq for linux
  TOUCH Release/obj.target/libzmq.stamp
  CXX(target) Release/obj.target/zmq/binding.o
  SOLINK_MODULE(target) Release/obj.target/zmq.node
make: Leaving directory '/tmp/apm-install-dir-2021316-60588-v18t2r.5ecp/node_modules/Hydrogen/node_modules/@aminya/zeromq/build'

npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
child process exited with code null
In file included from /home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13,
                 from /home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from ../binding.cc:24:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:307:49: warning: ‘BufferReference’ is deprecated: Use MemorySpan<const uint8_t> [-Wdeprecated-declarations]
  307 |   declarator __attribute__((deprecated(message)))
      |                                                 ^
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:4444:3: note: in expansion of macro ‘V8_DEPRECATED’
 4444 |   V8_DEPRECATED("Use CompiledWasmModule::GetWireBytesRef()",
      |   ^~~~~~~~~~~~~
In file included from ../binding.cc:24:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:4386:58: note: declared here
 4386 |   V8_DEPRECATED("Use MemorySpan<const uint8_t>", struct) BufferReference {
      |                                                          ^~~~~~~~~~~~~~~
In file included from /home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13,
                 from /home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from ../binding.cc:24:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:307:49: warning: ‘v8::WasmModuleObject::SerializedModule’ is deprecated: Use OwnedBuffer [-Wdeprecated-declarations]
  307 |   declarator __attribute__((deprecated(message)))
      |                                                 ^
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:4457:3: note: in expansion of macro ‘V8_DEPRECATED’
 4457 |   V8_DEPRECATED("Use CompiledWasmModule::Serialize()",
      |   ^~~~~~~~~~~~~
In file included from ../binding.cc:24:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:4380:55: note: declared here
 4380 |   std::pair<std::unique_ptr<const uint8_t[]>, size_t> SerializedModule;
      |                                                       ^~~~~~~~~~~~~~~~
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h: In member function ‘v8::Local<v8::Boolean> v8::Value::ToBoolean() const’:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:10172:62: warning: ‘v8::MaybeLocal<v8::Boolean> v8::Value::ToBoolean(v8::Local<v8::Context>) const’ is deprecated: ToBoolean can never throw. Use Local version. [-Wdeprecated-declarations]
10172 |   return ToBoolean(Isolate::GetCurrent()->GetCurrentContext())
      |                                                              ^
In file included from /home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13,
                 from /home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from ../binding.cc:24:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:2388:63: note: declared here
 2388 |                     V8_WARN_UNUSED_RESULT MaybeLocal<Boolean> ToBoolean(
      |                                                               ^~~~~~~~~
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
  322 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../binding.cc: In member function ‘void zmq::Socket::NotifyReadReady()’:
../binding.cc:399:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  399 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 0, NULL);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc:399:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  399 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 0, NULL);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc: In member function ‘void zmq::Socket::NotifySendReady()’:
../binding.cc:407:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  407 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 0, NULL);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc:407:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  407 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 0, NULL);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc: In member function ‘void zmq::Socket::MonitorEvent(uint16_t, int32_t, char*)’:
../binding.cc:458:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  458 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 4, argv);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc:458:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  458 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 4, argv);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc: In member function ‘void zmq::Socket::MonitorError(const char*)’:
../binding.cc:473:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  473 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 1, argv);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc:473:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  473 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 1, argv);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc: In static member function ‘static void zmq::Socket::UV_MonitorCallback(uv_timer_t*, int)’:
../binding.cc:545:98: warning: cast between incompatible function types from ‘void (*)(uv_timer_t*, int)’ {aka ‘void (*)(uv_timer_s*, int)’} to ‘uv_timer_cb’ {aka ‘void (*)(uv_timer_s*)’} [-Wcast-function-type]
  545 |       uv_timer_start(s->monitor_handle_, reinterpret_cast<uv_timer_cb>(Socket::UV_MonitorCallback), s->timer_interval_, 0);
      |                                                                                                  ^
../binding.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE zmq::Socket::Bind(Nan::NAN_METHOD_ARGS_TYPE)’:
../binding.cc:779:37: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  779 |                   (uv_after_work_cb)UV_BindAsyncAfter);
      |                                     ^~~~~~~~~~~~~~~~~
../binding.cc: In static member function ‘static void zmq::Socket::UV_BindAsyncAfter(uv_work_t*)’:
../binding.cc:814:70: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  814 |     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, 1, argv);
      |                                                                      ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc:814:70: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  814 |     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, 1, argv);
      |                                                                      ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE zmq::Socket::Unbind(Nan::NAN_METHOD_ARGS_TYPE)’:
../binding.cc:860:37: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  860 |                   (uv_after_work_cb)UV_UnbindAsyncAfter);
      |                                     ^~~~~~~~~~~~~~~~~~~
../binding.cc: In static member function ‘static void zmq::Socket::UV_UnbindAsyncAfter(uv_work_t*)’:
../binding.cc:893:70: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  893 |     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, 1, argv);
      |                                                                      ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc:893:70: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  893 |     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, 1, argv);
      |                                                                      ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE zmq::Socket::Monitor(Nan::NAN_METHOD_ARGS_TYPE)’:
../binding.cc:1122:103: warning: cast between incompatible function types from ‘void (*)(uv_timer_t*, int)’ {aka ‘void (*)(uv_timer_s*, int)’} to ‘uv_timer_cb’ {aka ‘void (*)(uv_timer_s*)’} [-Wcast-function-type]
 1122 |       uv_timer_start(socket->monitor_handle_, reinterpret_cast<uv_timer_cb>(Socket::UV_MonitorCallback), timer_interval, 0);
      |                                                                                                       ^
In file included from ../binding.cc:25:
../binding.cc: At global scope:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:560:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  560 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:594:3: note: in expansion of macro ‘NODE_MODULE_X’
  594 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../binding.cc:1558:1: note: in expansion of macro ‘NODE_MODULE’
 1558 | NODE_MODULE(zmq, init)
      | ^~~~~~~~~~~
In file included from ../binding.cc:24:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node_object_wrap.h:84:78:   required from here
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:9634:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
 9634 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../../nan/nan_object_wrap.h:65:61:   required from here
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:9634:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
g++: error: ./Release/../../zmq/lib/libzmq.a: No such file or directory
make: *** [zmq.target.mk:139: Release/obj.target/zmq.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-72-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-2021316-60588-v18t2r.5ecp/node_modules/Hydrogen/node_modules/@aminya/zeromq
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
child process exited with code null
In file included from /home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13,
                 from /home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from ../binding.cc:24:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:307:49: warning: ‘BufferReference’ is deprecated: Use MemorySpan<const uint8_t> [-Wdeprecated-declarations]
  307 |   declarator __attribute__((deprecated(message)))
      |                                                 ^
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:4444:3: note: in expansion of macro ‘V8_DEPRECATED’
 4444 |   V8_DEPRECATED("Use CompiledWasmModule::GetWireBytesRef()",
      |   ^~~~~~~~~~~~~
In file included from ../binding.cc:24:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:4386:58: note: declared here
 4386 |   V8_DEPRECATED("Use MemorySpan<const uint8_t>", struct) BufferReference {
      |                                                          ^~~~~~~~~~~~~~~
In file included from /home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13,
                 from /home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from ../binding.cc:24:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:307:49: warning: ‘v8::WasmModuleObject::SerializedModule’ is deprecated: Use OwnedBuffer [-Wdeprecated-declarations]
  307 |   declarator __attribute__((deprecated(message)))
      |                                                 ^
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:4457:3: note: in expansion of macro ‘V8_DEPRECATED’
 4457 |   V8_DEPRECATED("Use CompiledWasmModule::Serialize()",
      |   ^~~~~~~~~~~~~
In file included from ../binding.cc:24:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:4380:55: note: declared here
 4380 |   std::pair<std::unique_ptr<const uint8_t[]>, size_t> SerializedModule;
      |                                                       ^~~~~~~~~~~~~~~~
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h: In member function ‘v8::Local<v8::Boolean> v8::Value::ToBoolean() const’:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:10172:62: warning: ‘v8::MaybeLocal<v8::Boolean> v8::Value::ToBoolean(v8::Local<v8::Context>) const’ is deprecated: ToBoolean can never throw. Use Local version. [-Wdeprecated-declarations]
10172 |   return ToBoolean(Isolate::GetCurrent()->GetCurrentContext())
      |                                                              ^
In file included from /home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13,
                 from /home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from ../binding.cc:24:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:2388:63: note: declared here
 2388 |                     V8_WARN_UNUSED_RESULT MaybeLocal<Boolean> ToBoolean(
      |                                                               ^~~~~~~~~
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
  322 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../binding.cc: In member function ‘void zmq::Socket::NotifyReadReady()’:
../binding.cc:399:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  399 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 0, NULL);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc:399:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  399 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 0, NULL);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc: In member function ‘void zmq::Socket::NotifySendReady()’:
../binding.cc:407:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  407 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 0, NULL);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc:407:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  407 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 0, NULL);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc: In member function ‘void zmq::Socket::MonitorEvent(uint16_t, int32_t, char*)’:
../binding.cc:458:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  458 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 4, argv);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc:458:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  458 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 4, argv);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc: In member function ‘void zmq::Socket::MonitorError(const char*)’:
../binding.cc:473:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  473 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 1, argv);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc:473:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  473 |     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 1, argv);
      |                                                                         ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc: In static member function ‘static void zmq::Socket::UV_MonitorCallback(uv_timer_t*, int)’:
../binding.cc:545:98: warning: cast between incompatible function types from ‘void (*)(uv_timer_t*, int)’ {aka ‘void (*)(uv_timer_s*, int)’} to ‘uv_timer_cb’ {aka ‘void (*)(uv_timer_s*)’} [-Wcast-function-type]
  545 |       uv_timer_start(s->monitor_handle_, reinterpret_cast<uv_timer_cb>(Socket::UV_MonitorCallback), s->timer_interval_, 0);
      |                                                                                                  ^
../binding.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE zmq::Socket::Bind(Nan::NAN_METHOD_ARGS_TYPE)’:
../binding.cc:779:37: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  779 |                   (uv_after_work_cb)UV_BindAsyncAfter);
      |                                     ^~~~~~~~~~~~~~~~~
../binding.cc: In static member function ‘static void zmq::Socket::UV_BindAsyncAfter(uv_work_t*)’:
../binding.cc:814:70: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  814 |     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, 1, argv);
      |                                                                      ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc:814:70: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  814 |     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, 1, argv);
      |                                                                      ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE zmq::Socket::Unbind(Nan::NAN_METHOD_ARGS_TYPE)’:
../binding.cc:860:37: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  860 |                   (uv_after_work_cb)UV_UnbindAsyncAfter);
      |                                     ^~~~~~~~~~~~~~~~~~~
../binding.cc: In static member function ‘static void zmq::Socket::UV_UnbindAsyncAfter(uv_work_t*)’:
../binding.cc:893:70: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  893 |     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, 1, argv);
      |                                                                      ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc:893:70: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  893 |     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, 1, argv);
      |                                                                      ^
In file included from ../binding.cc:40:
../../../nan/nan.h:1026:46: note: declared here
 1026 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      |                                              ^~~~~~~~~~~~
../binding.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE zmq::Socket::Monitor(Nan::NAN_METHOD_ARGS_TYPE)’:
../binding.cc:1122:103: warning: cast between incompatible function types from ‘void (*)(uv_timer_t*, int)’ {aka ‘void (*)(uv_timer_s*, int)’} to ‘uv_timer_cb’ {aka ‘void (*)(uv_timer_s*)’} [-Wcast-function-type]
 1122 |       uv_timer_start(socket->monitor_handle_, reinterpret_cast<uv_timer_cb>(Socket::UV_MonitorCallback), timer_interval, 0);
      |                                                                                                       ^
In file included from ../binding.cc:25:
../binding.cc: At global scope:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:560:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  560 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:594:3: note: in expansion of macro ‘NODE_MODULE_X’
  594 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../binding.cc:1558:1: note: in expansion of macro ‘NODE_MODULE’
 1558 | NODE_MODULE(zmq, init)
      | ^~~~~~~~~~~
In file included from ../binding.cc:24:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node_object_wrap.h:84:78:   required from here
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:9634:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
 9634 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../../nan/nan_object_wrap.h:65:61:   required from here
/home/matt/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:9634:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
g++: error: ./Release/../../zmq/lib/libzmq.a: No such file or directory
make: *** [zmq.target.mk:139: Release/obj.target/zmq.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-72-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-2021316-60588-v18t2r.5ecp/node_modules/Hydrogen/node_modules/@aminya/zeromq
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @aminya/zeromq@5.2.15 build:libzmq: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @aminya/zeromq@5.2.15 build:libzmq script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/matt/.atom/.apm/_logs/2021-04-17T06_58_00_565Z-debug.log
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-2021316-60588-v18t2r.5ecp/package.json'
npm WARN apm-install-dir-2021316-60588-v18t2r.5ecp No description
npm WARN apm-install-dir-2021316-60588-v18t2r.5ecp No repository field.
npm WARN apm-install-dir-2021316-60588-v18t2r.5ecp No README data
npm WARN apm-install-dir-2021316-60588-v18t2r.5ecp No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @aminya/zeromq@5.2.15 install: `node-gyp-build || npm run build:libzmq`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @aminya/zeromq@5.2.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/matt/.atom/.apm/_logs/2021-04-17T06_58_01_058Z-debug.log

```

**Comment by aminya** [comment]
Could you run the following command and give me the output?

```
cd .atom/packages/hydrogen/node_modules/zeromq
node ./scripts/prepare.js
```

**Comment by mattcbro** [comment]
It seems the directory structure and files are not quite right for your suggestion.  First the hydrogen directory is capitalized to be Hydrogen.

```
cd ~/.atom/packages/Hydrogen/node_modules/zeromq
$ node ./scripts/prepare.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/matt/.atom/packages/Hydrogen/node_modules/zeromq/scripts/prepare.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```
So prepare.js does not exist.  Should I try a reinstall of something?
Thanks for you help.
```
$ ls scripts
build_libzmq.sh   download.js	       preinstall.js
cross_compile.sh  prebuild-install.js  publish_docs.sh
```

**Comment by aminya** [comment]
Your hydrogen is still old! Please remove this directory and run the following command again:
```
apm install hydrogen
```
There should be a `prepare.js` under the path you ran `ls`.

**Comment by mattcbro** [comment]
Well I "fixed" things by removing atom and then reinstalling it.  Searching through the packages in atom (v1.56) I don't see hydrogen at all,  even though most of the other packages are still running.  Is hydrogen no longer used for atom and the julia client?
