### ISSUE TITLE
Missing environment variables

### ISSUE THREAD

**Issue by dmotz** [nteract/hydrogen#404]
Sorry if this has been covered before, can't seem to find a solution.

When I examine `os.environ` from `jupyter` or `ipython3` or `python3` I can see all of my shell environment variables.

However when I run the same using Hydrogen (Python 3 kernel) in the latest version of Atom, many variables are missing. Specifically, I'm having problems with some CUDA variables needed for Python libraries. This is true whether I start Atom via the command line or otherwise.

Anything I might be missing? Is there a way to manually pass environment variables to Hydrogen?

**Comment by rgbkrk** [comment]
This sounds like we're not passing `process.env` on to the spawned process. Went ahead and made #405 for this.

**Comment by lgeiger** [comment]
Thanks for reporting. We just released `v0.12.3` to fix this.

**Comment by dmotz** [comment]
Thanks so much for your help. After finding `0.12.3` didn't solve my issue I did some digging and discovered that OSX 10.11 is known to remove both `LD_LIBRARY_PATH` and `DYLD_LIBRARY_PATH` environment variables while [SIP](https://en.wikipedia.org/wiki/System_Integrity_Protection) is turned on which is why they disappear from Atom's `process.env`.

While this is certainly not Hydrogen specific, I thought I'd leave this note here for anyone else stuck on trying to use CUDA libraries with it on OSX.

When I set the variables manually in `startKernel()` of `kernel-manager.coffee` like so, things work as expected in a Hydrogen session:

```coffeescript
process.env.LD_LIBRARY_PATH = process.env.DYLD_LIBRARY_PATH = '/usr/local/cuda/lib'
```

I attempted the same fix by using Hydrogen's Kernel Specs setting (`spec.env`), but haven't had any luck. Any issues obvious here?

```json
{
  "kernelspecs": {
    "python3": {
      "resource_dir": "/usr/local/share/jupyter/kernels/python3",
      "spec": {
        "language": "python",
        "display_name": "Python 3",
        "env": {
          "LD_LIBRARY_PATH": "/usr/local/cuda/lib",
          "DYLD_LIBRARY_PATH": "/usr/local/cuda/lib"
        },
        "argv": [
          "/usr/local/opt/python3/bin/python3.5",
          "-m",
          "ipykernel",
          "-f",
          "{connection_file}"
        ]
      }
    }
  }
}
```

**Comment by rgbkrk** [comment]
Oooooh, I don't think we've been using the env key in the spec there.

**Comment by lgeiger** [comment]
Now I know why I couldn't reproduce this issue. I followed [this guide](http://osxdaily.com/2015/10/05/disable-rootless-system-integrity-protection-mac-os-x/) to disable SIP.

**Comment by lgeiger** [comment]
> I attempted the same fix by using Hydrogen's Kernel Specs setting (spec.env), but haven't had any luck. Any issues obvious here?

We just released `v0.12.4`. This should work now.

**Comment by dmotz** [comment]
Thanks so much for looking into this! Hydrogen works perfectly with CUDA now.

**Comment by mscipio** [comment]
I think I have the very same problem on a fresh Atom+Hydrogen installation on Ubuntu 16.04.
```python
import os 
os.environ.keys['LD_LIBRARY_PATH']
```
Running this lines from terminal (after starting conda venv) allows me to see everything I automatically add to the path when starting the vEnv.
Doing the same within Atom gives me a `key-not-found` error ... I don't think I can use the solution discussed above, as it seems MacOS specific ...

**Comment by kylebarron** [comment]
The kernelspec isn't mac specific. Run `jupyter kernelspec list --json` to see the kernelspecs installed

**Comment by mscipio** [comment]
Yes, I know and I have all my 2 vEnv in there, but the only way I get the PATH and LD_LIBRARY_PATH correctly set is if I first start the vEnv, and *inside* it I run `atom --new-instance`

**Comment by kylebarron** [comment]
Yes, in order for Atom to inherit a shell's environment variables, it has to be started from inside that shell.
