### ISSUE TITLE
cannot scroll external window, and if I close it, it will left a blank space

### ISSUE THREAD

**Issue by SamaelChen** [nteract/hydrogen#999]
**Description:**

I cannot scroll external window, and if it is large, I cannot close it. However, if I close it, there will left a huge blank space.

**Steps to Reproduce:**

for first case

1. create a large dataframe and print it. It looks like:
![1](https://user-images.githubusercontent.com/5146128/30583680-3a880354-9d5a-11e7-93ed-e11da9c986d5.png)

for second case

1. open a small external window
2. close it. Then it looks like:
![2](https://user-images.githubusercontent.com/5146128/30584122-603b5ca8-9d5b-11e7-931c-c52ec1386492.png)
![3](https://user-images.githubusercontent.com/5146128/30584127-6511cc44-9d5b-11e7-9a33-c400acc4710a.png)

**Versions:**
OS: Ubuntu 16.04
Atom    : 1.19.6
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
Hydrogen: 1.22.0

**Logs:**

<embedded>:107334 IntersectionObserver.observe(target): target element is not a descendant of root.
TreeView @ <embedded>:107334
utils.js [sm]:138 Hydrogen: findCodeBlock: 0
utils.js [sm]:138 Hydrogen: KernelManager: startKernel: Python 3
utils.js [sm]:138 Hydrogen: ZMQKernel: monitor shellSocket
utils.js [sm]:138 Hydrogen: ZMQKernel: monitor controlSocket
utils.js [sm]:138 Hydrogen: ZMQKernel: monitor ioSocket
utils.js [sm]:138 Hydrogen: ZMQKernel: stdout: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049

utils.js [sm]:138 Hydrogen: ZMQKernel: stdout: To connect another client to this kernel, use:
    --existing kernel-44e96880-1ca3-4ae5-b9dc-203a889004f5.json

utils.js [sm]:138 Hydrogen: ZMQKernel: shellSocket connected
utils.js [sm]:138 Hydrogen: ZMQKernel: controlSocket connected
utils.js [sm]:138 Hydrogen: ZMQKernel: ioSocket connected
utils.js [sm]:138 Hydrogen: ZMQKernel: all main sockets connected
utils.js [sm]:138 Hydrogen: KernelManager: Executing startup code: %matplotlib inline
utils.js [sm]:138 Hydrogen: Kernel.execute: %matplotlib inline 

utils.js [sm]:138 Hydrogen: Kernel.execute: import pandas as pd
utils.js [sm]:138 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:138 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:138 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:138 Hydrogen: watchview running: 
utils.js [sm]:138 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:138 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:138 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:138 Hydrogen: watchview running: 
utils.js [sm]:138 Hydrogen: shell message: Message {idents: Array[0], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:138 Hydrogen: shell message: Message {idents: Array[0], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:138 Hydrogen: findCodeBlock: 2
utils.js [sm]:138 Hydrogen: Kernel.execute: pd.options.display.max_columns = None
utils.js [sm]:138 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:138 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:138 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:138 Hydrogen: watchview running: 
utils.js [sm]:138 Hydrogen: shell message: Message {idents: Array[0], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:138 Hydrogen: findCodeBlock: 5
utils.js [sm]:138 Hydrogen: Kernel.execute: '/mnt/share/Data/score/report_business_prediction.csv', sep=';')
utils.js [sm]:138 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:138 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:138 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:138 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}buffers: Array[0]content: Objectheader: Objectidents: Array[1]metadata: Objectparent_header: Object__proto__: Object
utils.js [sm]:138 Hydrogen: watchview running: 
utils.js [sm]:138 Hydrogen: shell message: Message {idents: Array[0], header: Object, parent_header: Object, metadata: Object, content: Object…}buffers: Array[0]content: Objectheader: Objectidents: Array[0]metadata: Objectparent_header: Object__proto__: Object
utils.js [sm]:138 Hydrogen: findCodeBlock: 7
utils.js [sm]:138 Hydrogen: Kernel.execute: business.head()
utils.js [sm]:138 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:138 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:138 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:138 Hydrogen: IO message: Message {idents: Array[1], header: Object, parent_header: Object, metadata: Object, content: Object…}
utils.js [sm]:138 Hydrogen: watchview running: 
utils.js [sm]:138 Hydrogen: shell message: Message {idents: Array[0], header: Object, parent_header: Object, metadata: Object, content: Object…}

**Comment by lgeiger** [comment]
This issue was fixed in Atom 1.19.7. Please upgrade to the latest version of Atom.

**Comment by SamaelChen** [comment]
I've upgraded Atom to 1.20.0 but I still cannot scroll the window. @lgeiger

**Comment by mattiasarro** [comment]
I also can't scroll the results view. `div.cell_display` expands to fit the content inside it, but horizontal scroll doesn't work. When I add `.cell_display { max-width: 1200px; }` (or whatever is guaranteed to fit on my screen) to my stylesheet, then the results area gets small and scrollable again. 

It makes sense that you can't scroll within the `div.cell_display` tag, as it's not overflowing width-wise. Either `atom-text-editor` should be scrollable along the whole width of `div.cell_display`, or `div.cell_display` should only expand to the visible area (which was the old behavior, before some upgrade).

I'm on Atom 1.20.0, Hydrogen 1.22.0, One Light UI theme, Atom Light syntax theme.

**Comment by BenRussert** [comment]
I have the width issue on atom `v1.20.1`, i'm guessing this is a platform specific thing since I am on ubuntu also. I bisected and found the commits in #975

**Comment by BenRussert** [comment]
@SamaelChen @mattiasarro Thanks for the report, this is fixed on master and should be released shortly.

I did not reproduce the second case @SamaelChen mentions, but if the next release doesnt fix it please let us know.

**Comment by SamaelChen** [comment]
@BenRussert The second case was fixed in Atom v1.20.0. Thanks.
